[build]
builder = "NIXPACKS"
buildCommand = "npm install && npx nx build frontend && npx nx build backend"

[deploy]
startCommand = "cd dist/apps/backend && node main.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 900
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
