[build]
builder = "DOCKERFILE"
buildCommand = "npm install --legacy-peer-deps && npx nx build frontend"

[deploy]
startCommand = "node apps/frontend/server.js"
healthcheckPath = "/"
healthcheckTimeout = 900
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
