[build]
builder = "DOCKERFILE"
buildCommand = "npm install && npx nx build frontend && npx nx build backend"

[deploy]
startCommand = "cd dist/apps/backend && node main.js"
healthcheckPath = "/"
healthcheckTimeout = 900
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
