[build]
builder = "DOCKERFILE"
buildCommand = "npm install --legacy-peer-deps && npx nx build frontend"

[deploy]
startCommand = "npx serve dist/apps/frontend"
healthcheckPath = "/"
healthcheckTimeout = 900
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

